const data = {
  1: {
    date: 'August 2014',
    title: 'My first love and partner in code',
    location: '',
    description: 'I ran my first marathon when I graduated from high school. To this day, running helps me debug my code and find effective solutions.',
    tag: 'hobby',
  },
  2: {
    date: 'January 2015 - September 2016',
    title: 'Introduction to tech',
    location: '',
    description: 'My first internship was translating scientific research to app developers. Our company tracked recovery metrics in elite athletes at the ALTIS training center in Phoenix Arizona.',
    tag: 'work',
  },
  3: {
    date: 'September 2016 - April 2018',
    title: 'Making an impact',
    location: '',
    description: "I worked with Dalhousie Varsity Athletics and Kinduct to create a coaching analytics program. This is where I first dabbled in coding using VBA. It's pretty cool to see that the program is now being offered varsity-wide!",
    tag: 'work',
  },
  4: {
    date: 'May 2016',
    title: 'Awarded Trainer of the Year',
    location: 'Dalhousie Varsity Athletics',
    description: '',
    tag: 'award',
  },
  5: {
    date: 'May 2018',
    title: 'Awarded Co-Curricular Record',
    location: '',
    description: 'An award by dalhousie to recognize out-of-classroom contributions.',
    tag: 'award',
  },
  6: {
    date: 'May 2019',
    title: 'Graduated with BSc Kinesiology',
    location: 'Dalhousie University',
    description: '',
    tag: 'education',
  },
  7: {
    date: 'November 2020',
    title: 'Continuing Education',
    location: '',
    description: 'I became a Certified Strengthening and Conditioning Specialist with the NSCA.',
    tag: 'education',
  },
  8: {
    date: 'September 2019 - April 2020',
    title: 'Putting education into practice',
    location: '',
    description: 'I trained for a 50k race. I enjoy preparing for endurance events in my free time.',
    tag: 'hobby',
  },
  9: {
    date: 'August 2020 - April 2022',
    title: 'Slowly returning to tech',
    location: 'Built with Science',
    description: "I contributed to the development of our company's CRM by utilizing an integrated tech stack consisting of Hubspot, Zapier, Shopify, and linked Google Sheets.",
    tag: 'work',
  },
  10: {
    date: 'January 2021 - April 2022',
    title: 'Reigniting my passion for development',
    location: '',
    description: 'I realized my affinity for programming when I started creating fully functional spreadsheets to model the MVP for our app development projects. This allowed me to effectively communicate the project requirements throughout the team.',
    tag: 'work',
  },
  11: {
    date: 'May 2022 - September 2022',
    title: 'Managing a remote team before returning to school',
    location: '',
    description: 'I managed a project that sold 1000+ courses in the first month! To ensure consistent branding and to help the designers, I upskilled in CSS.',
    tag: 'work',
  },
  12: {
    date: 'March 2023',
    title: 'Making the transition into full-time development',
    location: '',
    description: 'After years of working alongside developers, I finally earned a diploma in web development, allowing me to pursue my passion full-time.',
    tag: 'education',
  },
  13: {
    date: '2023 - present',
    title: 'Working on passion projects',
    location: '',
    description: 'Presently, I love working on new projects. In fact, my latest project is a super fun app that transforms your everyday diet into an epic space adventure!',
    tag: 'hobby',
  },
}

export default data;